In [9]:
import pandas as pd

dataset = pd.read_csv("manufacturing_dataset.csv",sep=";")

dataset.head()

,Production ID,Date,Product Type,Machine ID,Shift,Units Produced,Defects,Production Time Hours,Material Cost Per Unit,Labour Cost Per Hour,Energy Consumption kWh,Operator Count,Maintenance Hours,Down time Hours,Production Volume Cubic Meters,Scrap Rate,Rework Hours,Quality Checks Failed,Average Temperature C,Average Humidity Percent
0,1899-12-31,2020-01-01,Automotive,3,Eearly_Late,142,3.0,23.42,38.68,15.38,413.97,1,4.86,1.57,2.34,0.048,1.65,1,22.8,47.2
1,1900-01-01,2020-01-02,Textiles,8,Night,170,4.0,7.51,21.35,25.36,181.16,2,2.51,0.18,1.52,0.030,NaN,1,23.8,37.9
2,1900-01-02,2020-01-03,Appliances,11,Eearly_Late,182,4.0,20.58,47.54,16.46,452.15,2,0.34,2.88,0.57,0.026,0.26,0,24.5,56.1
3,1900-01-03,2020-01-04,Appliances,11,Day,133,NaN,21.68,40.21,28.70,485.78,3,4.64,2.23,1.90,0.036,NaN,2,22.3,50.8
4,1900-01-04,2020-01-05,Electronics,14,Night,82,NaN,16.68,38.02,17.20,315.58,1,2.29,0.02,2.25,0.020,0.67,0,23.4,53.9

In [ ]:
dataset.info()

<class 'pandas.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 20 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Production ID                   3000 non-null   str
 1   Date                            3000 non-null   str
 2   Product Type                    3000 non-null   str
 3   Machine ID                      3000 non-null   int64
 4   Shift                           3000 non-null   str
 5   Units Produced                  3000 non-null   int64
 6   Defects                         2701 non-null   float64
 7   Production Time Hours           3000 non-null   float64
 8   Material Cost Per Unit          3000 non-null   float64
 9   Labour Cost Per Hour            3000 non-null   float64
 10  Energy Consumption kWh          3000 non-null   float64
 11  Operator Count                  3000 non-null   int64
 12  Maintenance Hours               2700 non-null   float64
 13  Down time Hours                 2700 non-null   float64
 14  Production Volume Cubic Meters  3000 non-null   float64
 15  Scrap Rate                      3000 non-null   float64
 16  Rework Hours                    2700 non-null   float64
 17  Quality Checks Failed           3000 non-null   int64
 18  Average Temperature C           3000 non-null   float64
 19  Average Humidity Percent        3000 non-null   float64
dtypes: float64(12), int64(4), str(4)
memory usage: 468.9 KB

In [27]:
dataset.loc[dataset["Down time Hours"].isna()]

,Production ID,Date,Product Type,Machine ID,Shift,Units Produced,Defects,Production Time Hours,Material Cost Per Unit,Labour Cost Per Hour,Energy Consumption kWh,Operator Count,Maintenance Hours,Down time Hours,Production Volume Cubic Meters,Scrap Rate,Rework Hours,Quality Checks Failed,Average Temperature C,Average Humidity Percent
5,1900-01-05,2020-01-06,Automotive,1,Night,81,0.0,11.91,10.66,23.25,440.42,2,NaN,NaN,0.89,0.047,NaN,2,20.6,56.9
14,1900-01-14,2020-01-15,Furniture,17,Night,55,1.0,22.00,24.82,27.92,234.33,4,2.17,NaN,1.35,0.047,1.31,2,24.6,59.1
15,1900-01-15,2020-01-16,Automotive,3,Night,136,6.0,23.99,24.74,22.55,204.39,4,0.80,NaN,2.31,0.040,NaN,0,21.4,41.2
28,1900-01-28,2020-01-29,Appliances,12,Eearly_Late,95,3.0,7.07,13.70,23.63,254.49,2,3.86,NaN,1.10,0.049,1.54,0,19.1,42.3
43,1900-02-12,2020-02-13,Furniture,19,Eearly_Late,101,9.0,1.06,31.50,21.72,223.19,4,1.77,NaN,1.51,0.034,1.61,2,20.2,45.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2877,1907-11-17,2027-11-17,Automotive,2,Night,51,4.0,22.90,11.52,28.66,493.74,3,3.07,NaN,1.68,0.017,1.42,0,20.9,44.3
2902,1907-12-12,2027-12-12,Textiles,6,Day,68,0.0,19.29,25.68,27.22,217.64,3,3.79,NaN,2.47,0.042,NaN,0,20.0,57.7
2965,1908-02-13,2028-02-13,Automotive,3,Day,97,NaN,19.22,46.77,16.40,157.51,1,4.46,NaN,0.77,0.028,0.01,0,23.2,31.0
2982,1908-03-01,2028-03-01,Electronics,16,Day,140,6.0,14.63,49.78,15.78,383.41,4,0.68,NaN,2.32,0.045,1.89,2,20.1,30.2
2999,3000,2028-03-18,Appliances,12,Night,121,2.0,5.36,12.41,22.96,221.97,3,0.07,NaN,2.18,0.018,1.07,2,19.9,37.8